# Generated by Django 3.2.12 on 2022-09-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20220916_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['title'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='сategory',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='visit.subcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='visit.category', verbose_name='Категория'),
        ),
    ]
