# Generated by Django 3.2.12 on 2022-09-15 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20220916_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='visit.category', verbose_name='Подкатегория'),
        ),
    ]
