# Generated by Django 3.2.12 on 2022-09-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='visit.category', verbose_name='Категория'),
        ),
    ]
