# Generated by Django 4.1.1 on 2022-09-17 17:28

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_auto_20220916_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='visit.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, on_delete=django.db.models.deletion.CASCADE, to='visit.subcategory'),
        ),
    ]
