# Generated by Django 4.1.1 on 2022-09-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0009_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('mail', models.EmailField(max_length=254, null=True, verbose_name='Электронная почта')),
                ('message', models.CharField(max_length=150, null=True, verbose_name='Сообщение')),
            ],
        ),
    ]
