# Generated by Django 4.1.1 on 2022-09-25 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0010_contactform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['name'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AddField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 25, 10, 25, 41, 125844, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='mail',
            field=models.EmailField(default=datetime.datetime(2022, 9, 25, 10, 25, 46, 573167, tzinfo=datetime.timezone.utc), max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.CharField(default='test', max_length=150, verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(default='test', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
