# Generated by Django 4.1.1 on 2022-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0011_alter_contactform_options_contactform_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
    ]
