# Generated by Django 4.1.1 on 2022-09-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0012_malling_alter_contactform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malling',
            name='mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
