# Generated by Django 3.2.12 on 2022-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0013_alter_malling_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='sity',
            field=models.CharField(default=0, max_length=150, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
