# Generated by Django 3.2.12 on 2022-10-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0014_contactform_sity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(max_length=150, verbose_name='Сообщение'),
        ),
    ]
