# Generated by Django 3.2.12 on 2022-10-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0016_auto_20221007_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedcombination',
            options={'verbose_name': 'Комбинацию', 'verbose_name_plural': 'Комбинации'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['title'], 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_2',
            field=models.CharField(max_length=150, null=True, verbose_name='Код Товара 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_3',
            field=models.CharField(max_length=150, null=True, verbose_name='Код Товара 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_2',
            field=models.CharField(max_length=150, null=True, verbose_name='Вес продукции 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_3',
            field=models.CharField(max_length=150, null=True, verbose_name='Вес продукции 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=150, null=True, verbose_name='Код Товара 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=150, null=True, verbose_name='Вес продукции 1'),
        ),
    ]
