# Generated by Django 3.2.12 on 2022-10-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0017_auto_20221008_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code_4',
            field=models.CharField(max_length=150, null=True, verbose_name='Код Товара 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_5',
            field=models.CharField(max_length=150, null=True, verbose_name='Код Товара 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code_6',
            field=models.CharField(max_length=150, null=True, verbose_name='Код Товара 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_4',
            field=models.CharField(max_length=150, null=True, verbose_name='Вес продукции 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_5',
            field=models.CharField(max_length=150, null=True, verbose_name='Вес продукции 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_6',
            field=models.CharField(max_length=150, null=True, verbose_name='Вес продукции 6'),
        ),
    ]
