# Generated by Django 3.2.12 on 2022-10-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0020_subcategory_parent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
