# Generated by Django 3.2.12 on 2022-10-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0021_auto_20221010_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_before_date',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, max_length=355, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Энергетическая ценность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_value_of_100_grams',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пищевая ценность 100 грамм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_is_for',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цена указана за'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код Товара 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код Товара 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код Товара 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код Товара 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code_5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код Товара 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code_6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Код Товара 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_packaging',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип упаковки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вес продукции 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вес продукции 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вес продукции 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вес продукции 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вес продукции 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Вес продукции 6'),
        ),
    ]
