# Generated by Django 3.2.12 on 2022-10-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0022_auto_20221011_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='parent_category',
            new_name='category',
        ),
    ]
