# Generated by Django 3.2.12 on 2022-10-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0025_auto_20221012_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaruselProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Карусель Продуктов',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='CatalogFile')),
            ],
            options={
                'verbose_name': 'Файл каталога',
                'verbose_name_plural': 'Файлы каталога',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнёра',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото продукта'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='caruselproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.product', verbose_name='Продукт'),
        ),
    ]
