# Generated by Django 3.2.12 on 2022-10-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0026_auto_20221012_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogfile',
            name='file',
            field=models.FileField(upload_to='CatalogFile', verbose_name='Файл'),
        ),
    ]
