# Generated by Django 3.2.12 on 2022-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0029_auto_20221015_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogfile',
            options={'ordering': ['id'], 'verbose_name': 'Прайслист', 'verbose_name_plural': 'Прайслист'},
        ),
        migrations.AlterField(
            model_name='product',
            name='prise_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цена продукции 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prise_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цена продукции 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prise_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цена продукции 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prise_5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цена продукции 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prise_6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цена продукции 6'),
        ),
    ]
