# Generated by Django 3.2.12 on 2022-10-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0030_auto_20221017_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['the_order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
