# Generated by Django 3.2.12 on 2022-10-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0031_auto_20221017_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='the_order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
