# Generated by Django 3.2.12 on 2022-10-17 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0032_alter_category_the_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='the_order',
            new_name='order',
        ),
    ]
