# Generated by Django 3.2.12 on 2022-10-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0033_auto_20221017_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code_6',
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_packaging_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип упаковки 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_packaging_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип упаковки 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_packaging_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип упаковки 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_packaging_5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип упаковки 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_packaging_6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип упаковки 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_packaging',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип упаковки 1'),
        ),
    ]
