# Generated by Django 3.2.12 on 2022-10-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0034_auto_20221017_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_from',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Количечтво от 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_from_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Количечтво от 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_from_3',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Количечтво от 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_from_4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Количечтво от 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_from_5',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Количечтво от 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_from_6',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Количечтво от 6'),
        ),
    ]
